apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-vol-{{ .Values.postgres.name }}
  namespace: {{ .Release.Namespace }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.postgres.persistence.size | quote }}
  storageClassName: {{ .Values.postgres.persistence.storageClass }}
---
