apiVersion: v1
kind: Secret
metadata:
  name: {{ include "postgres.secret.name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ include "postgres.secret.name" . }}
type: Opaque
data:
  {{- if and .Values.postgres.postgresqlPostgresPassword (not (eq .Values.postgres.postgresqlUsername "postgres")) }}
  postgresql-postgres-password: {{ include "postgresql.postgres.password" . | b64enc | quote }}
  {{- end }}
  postgresql-password: {{ include "postgresql.password" . | b64enc | quote }}
---
